### ISSUE TITLE
Artifact path seems to contain a double `//` in the key

### ISSUE THREAD

**Issue by lorengordon** [plus3it/terrafirm#24]
Compare:

* https://s3.console.aws.amazon.com/s3/buckets/terrafirm/20180308/1557_0e502a18c510
* https://s3.console.aws.amazon.com/s3/buckets/terrafirm/20180308/1557_0e502a18c510/

**Comment by YakDriver** [comment]
There are no double slashes. What is happening here is that without the trailing slash, s3 first looks for an object named "1557_0e502a18c510" with a key prefix of "20180308". Since it doesn't find that, it then looks for an index page (e.g., index.html). Since it doesn't find that, it returns a 302 redirect which shows up as a nameless key based on our settings. Bottom line, trailing slashes are not optional for going directly to a listing of objects with a given prefix.

https://docs.aws.amazon.com/AmazonS3/latest/dev/IndexDocumentSupport.html
